### ISSUE TITLE
PyQt5 version requirement breaks environment

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/napari-time-slicer#3]
Hi @haesleinhuepf ,

I wanted to ask whether it is really strictly necessary to use the current PyQt5 requirement?

```
pyqt5>=5.15.0
```

It collides with current Spyder versions that only support PyQt up to 5.13:
```
spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.
spyder 5.1.5 requires pyqt5<5.13, but you have pyqt5 5.15.6 which is incompatible.
```

Since the time slicer is used downstream in quite a few plugins of yours (e.g., segment-blobs-and-things-with-membranes, etc.) this is quite a restriction.

**Comment by haesleinhuepf** [comment]
Hi Johannes @jo-mueller ,

can you try with a local copy of `time-slicer` from master without that requirement, if [this bug](https://github.com/napari/napari/issues/3704#issuecomment-980749276) happens on your machine? I just added this dependency because of this bug...

**Comment by jo-mueller** [comment]
> can you try with a local copy of time-slicer from master without that requirement, if this bug happens on your machine?

Yes, it does - dang

**Comment by haesleinhuepf** [comment]
See also:
https://github.com/spyder-ide/spyder/issues/12829

**Comment by jo-mueller** [comment]
>See also: spyder-ide/spyder#12829

*sigh*

Is this an issue in PyCharm as well? Or does this sort of error (PyQt5 incompatibility breaking spyder or oother packages) simply not occur there?

**Comment by haesleinhuepf** [comment]
Pycharm doesn't run in a conda environment, it's a standalone application, written in C++ I think, If you're thinking of trying another IDE, consider [code](https://code.visualstudio.com/), it's very popular in the napari/scipy/scikit-image community.

**Comment by jo-mueller** [comment]
Alright - Running Spyder in its own environment and simply switching the interpreter/environment solves this. I'll close this issue, then.
