### ISSUE TITLE
Bug report: `KeyError: 'viewer'`

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/napari-time-slicer#7]
Hi @haesleinhuepf ,

I am getting an error in [this notebook](https://github.com/BiAPoL/napari-stress/blob/expose-surface-tracing-to-napari/docs/tutorials/demo/demo_surface_tracing.ipynb) in the 5th cell on this command:

```Python
surface = nppas.largest_label_to_surface(labels)
```

where `nppas` is `napari-process-points-and-surfaces`. Labels is a regular label image as made with `skimage.measure.label()`.

Thanks for looking at it!

**Comment by jo-mueller** [comment]
Add-on: Using `nppas.largest_label_to_surface(labels)` throws the above error, whereas `nppas.label_to_surface(labels, 1)` works.

**Comment by haesleinhuepf** [comment]
This was fixed in napari-time-slicer 0.4.5

Thanks for reporting @jo-mueller !
